name: RELEASE-IMAGE

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The tag name of image'
        required: true
        default: ''
  release:
    types:
      - published

env:
  RELEASE_VERSION: ${{ github.ref_name }}


jobs:
  release-version:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.get_release_version.outputs.release_version }}
    steps:
      - name: Get Release Version
        id: get_release_version
        run: |
          RELEASE_VERSION=${{ inputs.release_version }}
          if [ -z "$RELEASE_VERSION" ]; then
              RELEASE_VERSION=${{ env.RELEASE_VERSION }}
          fi
          echo release_version=$RELEASE_VERSION >> $GITHUB_OUTPUT

  release-image:
    permissions:
      id-token: write
      contents: read
    needs: [ release-version ]
    uses: apecloud-inc/apecloud-cd/.github/workflows/release-image-cache.yml@v0.3.0
    with:
      IMG: "apecloud/polardbx-tools"
      VERSION: "${{ needs.release-version.outputs.release-version }}"
      DOCKERFILE_PATH: "./Dockerfile"
      APECD_REF: "v0.3.0"
      BUILDX_PLATFORMS: "linux/amd64"
    secrets: inherit
